name: Test Metrics

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm ci

      - name: Run tests and collect metrics
        run: |
          # Run the tests with Jest and collect the metrics
          npx jest --json --outputFile=test-results.json

      - name: Comment on pull request
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            **Test Metrics:**

            ```json
            ${{ steps.<previous-step-id>.outputs.testMetrics }}
            ```
